version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=test-cluster
      - CORE_CONF_fs_defaultFS=hdfs://0.0.0.0:9000 # Слушать на всех интерфейсах
      - HDFS_CONF_dfs_replication=1
    ports:
      - "9870:9870" # Web UI
      - "9000:9000" # RPC
    volumes:
      - namenode-data:/hadoop/dfs/name
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://0.0.0.0:9000 # Слушать на всех интерфейсах
      - HDFS_CONF_dfs_replication=1
    ports:
      - "9864:9864" # Web UI
      - "50010:50010" # Data Transfer Port
      - "50020:50020" # IPC Port
      - "50075:50075" # HTTP Server Port
    volumes:
      - datanode-data:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop

volumes:
  namenode-data:
  datanode-data:

networks:
  hadoop: